Add packit support
Katello/hammer-cli-katello pull request #934
Opened 2024-04-25 14:43 UTC by ianballou

I used hammer-cli-foreman's packit file as an example.

2024-04-25 14:52 UTC, ianballou commented
/packit build

2024-04-25 14:52 UTC, ianballou commented
/packit test

2024-04-25 16:54 UTC, chris1984 approved these changes
ACK

2024-04-25 18:26 UTC, ianballou commented
https://github.com/theforeman/foreman-packaging/pull/10731 will fix the builds

2024-05-02 08:17 UTC, ekohl requested changes
I'd also drop the test deps from the gemspec to avoid duplication

2024-05-02 08:17 UTC, ekohl commented on gemfile.d/test.rb
> +  gem 'ci_reporter', '>= 1.6.3', "< 2.0.0"
This one was for Jenkins. I don't think it supports GHA

2024-05-02 08:17 UTC, ekohl commented on Gemfile
> +Dir[File.join(__dir__, 'gemfile.d', '*.rb')].each do |bundle|
There's no need for this here. You can just define it in the Gemfile itself. Gemfile.d is for Foreman plugins.

While we don't use it today, dependabot doesn't support `eval_gemfile` so I'd stick to a plain Gemfile.

Though the instance_eval above already breaks dependabot.

2024-05-06 16:55 UTC, ianballou commented
This PR should fix our nightly builds, which folks are waiting to test.

2024-05-06 17:28 UTC, ekohl commented on gemfile.d/test.rb
> +  gem 'ci_reporter', '>= 1.6.3', "< 2.0.0"
If you're dropping the use of it, you can also drop the dependency
```suggestion
```

2024-05-07 18:17 UTC, ianballou commented
@ekohl thanks for catching the gemfile folder, it's deleted now.

2024-05-07 18:29 UTC, ianballou commented
Did a quick test, my PR doesn't seem to break anything in h-c-k at least.

2024-05-07 18:42 UTC, chris1984 approved these changes

2024-05-07 19:44 UTC, ianballou commented
Merging since it _should_ help with nightly, but we can make further improvements as needed.

2024-05-07 19:44 UTC, merged