Fixes #37993 - Update cvpurge count to a better description
Katello/hammer-cli-katello pull request #968
Opened 2024-11-07 20:33 UTC by chris1984

* The `--count` parameter was causing confusion amongst users which lead them to believe that is how many versions to purge instead of keep.
* Renamed the param to `--versions-to-keep` and updated the options in the code and in the tests.
* The code looks like this which determines how many versions to delete `versions_to_purge = old_unused_versions.slice(0, old_unused_versions.size - option_versions_to_keep)`

### To test
* Create a content view and publish 4 versions
* If you don't pase in `versions-to-keep` the default is 3 it will remove 1 version
* Create a few more published versions of that content view
* Pass in how many you want to keep and issue the command to make sure it deletes the versions that are unused minus how many you want to keep.

2024-11-13 14:32 UTC, qcjames53 requested changes
Hi Chris! I was able to verify that the hammer field works properly with a variety of inputs. I could see it still being confusing for users that the number of CVVs remaining is one (or more) more than the "versions to keep" flag they passed in, but I do think the help text does a good job of showing that it's the unused CVVs. Since this isn't changing any of the functionality of this command, I'm totally okay with how purge functions.

The source looks good to me but I'd love if you could split the long source lines instead of disabling the limit.

2024-11-13 14:32 UTC, qcjames53 commented on lib/hammer_cli_katello/content_view_purge.rb
> +    # rubocop:disable Layout/LineLength
If you wouldn't mind, please remove this linelength limit and split the long lines 54 and 63 into smaller lines.

2024-11-13 14:32 UTC, qcjames53 commented on test/functional/content_view/purge_test.rb
> +      # rubocop:disable Layout/LineLength
Same here for 57, please:
```
      assert(r.err.include?(
        'Invalid value for --versions-to-keep option'),
        'Incorrect error message'
      )
```

2024-11-13 18:47 UTC, parthaa commented on lib/hammer_cli_katello/content_view_purge.rb
> -    option "--count", "COUNT", _("count of unused versions to keep"),
check on deprecation

2024-11-14 18:36 UTC, qcjames53 commented
Wanted to get this down in writing before I forget:

We discussed changing the linelength config for rubocop hammer to match rubocop katello because they are so different. Katello is set up for length 200 at the moment. I'm totally okay with these changes and that would let the longer lines here through without modification.

2024-11-18 20:57 UTC, chris1984 commented
@qcjames53 how does this look:
#### Help
```bash
[vagrant@ip-10-0-168-55 hammer-cli-katello]$ hammer content-view purge -h
Usage:
    hammer content-view purge [OPTIONS]

Options:
 --async                          Do not wait for the task
 --count NUMBER                   (deprecated) Number of versions to keep
                                  Default: 3
 --id VALUE                       Content View numeric identifier
 --name VALUE                     Content View name
 --organization[-id|-label] VALUE Organization name/label/id to search by
 --versions-to-keep NUMBER        Number of unused versions to keep
                                  Default: 3
 -h, --help                       Print help
```

#### Command showing the deprecation warning:
```bash
[vagrant@ip-10-0-168-55 hammer-cli-katello]$ hammer content-view purge --organization-id 1 --id 5 --count 3
The --count option is deprecated and will be removed in the next release.
[.................................................................................................................................................................................................................................................................................................................................................................................] [100%]
Version '1.0' of content view 'Test-Purge' deleted.
```

2024-11-20 14:15 UTC, qcjames53 approved these changes
The new help text looks great to me; both options have appropriate descriptions. I was able to trigger the deprecation warning when running `--count`. Functionality for both purge options seems to work. The unit tests seem to work well. ACKing :)

2024-11-20 15:41 UTC, merged